name: Check New Features

env:
  OPENROAD_REPO: https://github.com/The-OpenROAD-Project/OpenROAD.git
  OPENROAD_DIRECTORY: OpenROAD
  APT_PACKAGES_FILE: .github/workflows/apt-packages.txt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-new-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone OpenROAD
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'The-OpenROAD-Project'
          repository: 'OpenROAD'
      - name: Install Apt Packages
        run: sudo apt install -y $(cat $APT_PACKAGES_FILE)
      - name: Install Python Requirements
        run: python3 -m pip install -r requirements.txt
      - name: Generate Commands
        run: python3 tcl_commands_to_file_tree.py $OPENROAD_DIRECTORY
