name: Check New Features

env:
  OPENROAD_REPO: https://github.com/The-OpenROAD-Project/OpenROAD.git
  OPENROAD_DIRECTORY: openroad
  APT_PACKAGES_FILE: .github/workflows/apt-packages.txt

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

jobs:
  check-new-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone OpenROAD
        run: git clone $OPENROAD_REPO $OPENROAD_DIRECTORY
      - name: Install Apt Packages
        run: sudo apt install -y $(cat $APT_PACKAGES_FILE)
      - name: Install Python Requirements
        run: python3 -m pip install -r requirements.txt
      - name: Set Output Directory
        run: echo "OUTPUT_DIRECTORY=commands/$(date +%F)-$(git -C $OPENROAD_DIRECTORY rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Generate Commands
        run: |
          python3 tcl_commands_to_file_tree.py $OPENROAD_DIRECTORY\
            --output-dir $OUTPUT_DIRECTORY
      #      - name: Push Results
      #        run: |
      #          git config --local user.name "github-actions[bot]"
      #          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #          git add $OUTPUT_DIRECTORY
      #          git commit -m "Generate and Add '$OUTPUT_DIRECTORY'" && git push
      - name: Diff
        run: |
          cd commands
          diff -r --side-by-side --suppress-common-lines $(find . -maxdepth 1 -mindepth 1 -type d -printf "%p\n" | sort -n | tail -n 2) --side-by-side || true

