name: Check New Features

env:
  OPENROAD_REPO: https://github.com/The-OpenROAD-Project/OpenROAD.git

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Check New Features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone OpenROAD
        run: git clone $OPENROAD_REPO
